services:
  db:
    image: postgres:17
    container_name: bugodex-db

    environment:
      POSTGRES_DB: bugodex
      POSTGRES_USER: bugodex
      POSTGRES_PASSWORD: bugodex

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: